#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using iBill.Data;

namespace iBill.Data	
{
	public partial class iBillEntities : OpenAccessContext, IiBillEntitiesUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public iBillEntities()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public iBillEntities(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public iBillEntities(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public iBillEntities(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public iBillEntities(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<User> Users 
		{
			get
			{
				return this.GetAll<User>();
			}
		}
		
		public IQueryable<System> Systems 
		{
			get
			{
				return this.GetAll<System>();
			}
		}
		
		public IQueryable<Status> Status 
		{
			get
			{
				return this.GetAll<Status>();
			}
		}
		
		public IQueryable<Specialitycode> Specialitycodes 
		{
			get
			{
				return this.GetAll<Specialitycode>();
			}
		}
		
		public IQueryable<Scheduleofbenefit> Scheduleofbenefits 
		{
			get
			{
				return this.GetAll<Scheduleofbenefit>();
			}
		}
		
		public IQueryable<Reconcile> Reconciles 
		{
			get
			{
				return this.GetAll<Reconcile>();
			}
		}
		
		public IQueryable<Recitem> Recitems 
		{
			get
			{
				return this.GetAll<Recitem>();
			}
		}
		
		public IQueryable<Quickprocedure> Quickprocedures 
		{
			get
			{
				return this.GetAll<Quickprocedure>();
			}
		}
		
		public IQueryable<Quickpremium> Quickpremia 
		{
			get
			{
				return this.GetAll<Quickpremium>();
			}
		}
		
		public IQueryable<Province> Provinces 
		{
			get
			{
				return this.GetAll<Province>();
			}
		}
		
		public IQueryable<Provider> Providers 
		{
			get
			{
				return this.GetAll<Provider>();
			}
		}
		
		public IQueryable<Paycode> Paycodes 
		{
			get
			{
				return this.GetAll<Paycode>();
			}
		}
		
		public IQueryable<Patient> Patients 
		{
			get
			{
				return this.GetAll<Patient>();
			}
		}
		
		public IQueryable<Myscheduleofbenefit> Myscheduleofbenefits 
		{
			get
			{
				return this.GetAll<Myscheduleofbenefit>();
			}
		}
		
		public IQueryable<Myfacility> Myfacilities 
		{
			get
			{
				return this.GetAll<Myfacility>();
			}
		}
		
		public IQueryable<Mydiagnosticcode> Mydiagnosticcodes 
		{
			get
			{
				return this.GetAll<Mydiagnosticcode>();
			}
		}
		
		public IQueryable<Mriclaim> Mriclaims 
		{
			get
			{
				return this.GetAll<Mriclaim>();
			}
		}
		
		public IQueryable<Mribill> Mribills 
		{
			get
			{
				return this.GetAll<Mribill>();
			}
		}
		
		public IQueryable<Mohreject> Mohrejects 
		{
			get
			{
				return this.GetAll<Mohreject>();
			}
		}
		
		public IQueryable<Mohreconcile> Mohreconciles 
		{
			get
			{
				return this.GetAll<Mohreconcile>();
			}
		}
		
		public IQueryable<Mohoffice> Mohoffices 
		{
			get
			{
				return this.GetAll<Mohoffice>();
			}
		}
		
		public IQueryable<Groupmd> Groupmds 
		{
			get
			{
				return this.GetAll<Groupmd>();
			}
		}
		
		public IQueryable<Facility> Facilities 
		{
			get
			{
				return this.GetAll<Facility>();
			}
		}
		
		public IQueryable<Edtfile> Edtfiles 
		{
			get
			{
				return this.GetAll<Edtfile>();
			}
		}
		
		public IQueryable<Edt> Edts 
		{
			get
			{
				return this.GetAll<Edt>();
			}
		}
		
		public IQueryable<Doctor> Doctors 
		{
			get
			{
				return this.GetAll<Doctor>();
			}
		}
		
		public IQueryable<Diagnosticcode> Diagnosticcodes 
		{
			get
			{
				return this.GetAll<Diagnosticcode>();
			}
		}
		
		public IQueryable<Claim> Claims 
		{
			get
			{
				return this.GetAll<Claim>();
			}
		}
		
		public IQueryable<Bill> Bills 
		{
			get
			{
				return this.GetAll<Bill>();
			}
		}
		
		public IQueryable<Batch> Batches 
		{
			get
			{
				return this.GetAll<Batch>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			backend.Logging.MetricStoreSnapshotInterval = 0;
			return backend;
		}
	}
	
	public interface IiBillEntitiesUnitOfWork : IUnitOfWork
	{
		IQueryable<User> Users
		{
			get;
		}
		IQueryable<System> Systems
		{
			get;
		}
		IQueryable<Status> Status
		{
			get;
		}
		IQueryable<Specialitycode> Specialitycodes
		{
			get;
		}
		IQueryable<Scheduleofbenefit> Scheduleofbenefits
		{
			get;
		}
		IQueryable<Reconcile> Reconciles
		{
			get;
		}
		IQueryable<Recitem> Recitems
		{
			get;
		}
		IQueryable<Quickprocedure> Quickprocedures
		{
			get;
		}
		IQueryable<Quickpremium> Quickpremia
		{
			get;
		}
		IQueryable<Province> Provinces
		{
			get;
		}
		IQueryable<Provider> Providers
		{
			get;
		}
		IQueryable<Paycode> Paycodes
		{
			get;
		}
		IQueryable<Patient> Patients
		{
			get;
		}
		IQueryable<Myscheduleofbenefit> Myscheduleofbenefits
		{
			get;
		}
		IQueryable<Myfacility> Myfacilities
		{
			get;
		}
		IQueryable<Mydiagnosticcode> Mydiagnosticcodes
		{
			get;
		}
		IQueryable<Mriclaim> Mriclaims
		{
			get;
		}
		IQueryable<Mribill> Mribills
		{
			get;
		}
		IQueryable<Mohreject> Mohrejects
		{
			get;
		}
		IQueryable<Mohreconcile> Mohreconciles
		{
			get;
		}
		IQueryable<Mohoffice> Mohoffices
		{
			get;
		}
		IQueryable<Groupmd> Groupmds
		{
			get;
		}
		IQueryable<Facility> Facilities
		{
			get;
		}
		IQueryable<Edtfile> Edtfiles
		{
			get;
		}
		IQueryable<Edt> Edts
		{
			get;
		}
		IQueryable<Doctor> Doctors
		{
			get;
		}
		IQueryable<Diagnosticcode> Diagnosticcodes
		{
			get;
		}
		IQueryable<Claim> Claims
		{
			get;
		}
		IQueryable<Bill> Bills
		{
			get;
		}
		IQueryable<Batch> Batches
		{
			get;
		}
	}
}
namespace iBill.Data	
{
	public partial class User
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private string _userPassword;
		public virtual string UserPassword
		{
			get
			{
				return this._userPassword;
			}
			set
			{
				this._userPassword = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private string _billingCode;
		public virtual string BillingCode
		{
			get
			{
				return this._billingCode;
			}
			set
			{
				this._billingCode = value;
			}
		}
		
		private string _specialityCode;
		public virtual string SpecialityCode
		{
			get
			{
				return this._specialityCode;
			}
			set
			{
				this._specialityCode = value;
			}
		}
		
		private string _facilityCode;
		public virtual string FacilityCode
		{
			get
			{
				return this._facilityCode;
			}
			set
			{
				this._facilityCode = value;
			}
		}
		
		private string _locCode;
		public virtual string LocCode
		{
			get
			{
				return this._locCode;
			}
			set
			{
				this._locCode = value;
			}
		}
		
		private string _groupNumber;
		public virtual string GroupNumber
		{
			get
			{
				return this._groupNumber;
			}
			set
			{
				this._groupNumber = value;
			}
		}
		
		private string _mOHOffice;
		public virtual string MOHOffice
		{
			get
			{
				return this._mOHOffice;
			}
			set
			{
				this._mOHOffice = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _province;
		public virtual string Province
		{
			get
			{
				return this._province;
			}
			set
			{
				this._province = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _phone;
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				this._phone = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _reg1;
		public virtual string Reg1
		{
			get
			{
				return this._reg1;
			}
			set
			{
				this._reg1 = value;
			}
		}
		
		private string _reg2;
		public virtual string Reg2
		{
			get
			{
				return this._reg2;
			}
			set
			{
				this._reg2 = value;
			}
		}
		
		private string _reg3;
		public virtual string Reg3
		{
			get
			{
				return this._reg3;
			}
			set
			{
				this._reg3 = value;
			}
		}
		
		private string _reg4;
		public virtual string Reg4
		{
			get
			{
				return this._reg4;
			}
			set
			{
				this._reg4 = value;
			}
		}
		
		private double? _pTolerance;
		public virtual double? PTolerance
		{
			get
			{
				return this._pTolerance;
			}
			set
			{
				this._pTolerance = value;
			}
		}
		
		private short? _isGroup;
		public virtual short? IsGroup
		{
			get
			{
				return this._isGroup;
			}
			set
			{
				this._isGroup = value;
			}
		}
		
		private IList<Mriclaim> _mriclaims = new List<Mriclaim>();
		public virtual IList<Mriclaim> Mriclaims
		{
			get
			{
				return this._mriclaims;
			}
		}
		
		private IList<Mribill> _mribills = new List<Mribill>();
		public virtual IList<Mribill> Mribills
		{
			get
			{
				return this._mribills;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class System
	{
		private string _errCode;
		public virtual string ErrCode
		{
			get
			{
				return this._errCode;
			}
			set
			{
				this._errCode = value;
			}
		}
		
		private string _sysName;
		public virtual string SysName
		{
			get
			{
				return this._sysName;
			}
			set
			{
				this._sysName = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Status
	{
		private string _status1;
		public virtual string Status1
		{
			get
			{
				return this._status1;
			}
			set
			{
				this._status1 = value;
			}
		}
		
		private string _statusName;
		public virtual string StatusName
		{
			get
			{
				return this._statusName;
			}
			set
			{
				this._statusName = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Specialitycode
	{
		private string _specialityCode;
		public virtual string SpecialityCode
		{
			get
			{
				return this._specialityCode;
			}
			set
			{
				this._specialityCode = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Scheduleofbenefit
	{
		private string _serviceCode;
		public virtual string ServiceCode
		{
			get
			{
				return this._serviceCode;
			}
			set
			{
				this._serviceCode = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _mOHPage;
		public virtual string MOHPage
		{
			get
			{
				return this._mOHPage;
			}
			set
			{
				this._mOHPage = value;
			}
		}
		
		private decimal? _feeGeneral;
		public virtual decimal? FeeGeneral
		{
			get
			{
				return this._feeGeneral;
			}
			set
			{
				this._feeGeneral = value;
			}
		}
		
		private decimal? _feeSpecialist;
		public virtual decimal? FeeSpecialist
		{
			get
			{
				return this._feeSpecialist;
			}
			set
			{
				this._feeSpecialist = value;
			}
		}
		
		private decimal? _feeAssistant;
		public virtual decimal? FeeAssistant
		{
			get
			{
				return this._feeAssistant;
			}
			set
			{
				this._feeAssistant = value;
			}
		}
		
		private int? _unitsAssistant;
		public virtual int? UnitsAssistant
		{
			get
			{
				return this._unitsAssistant;
			}
			set
			{
				this._unitsAssistant = value;
			}
		}
		
		private decimal? _feeAnesthesia;
		public virtual decimal? FeeAnesthesia
		{
			get
			{
				return this._feeAnesthesia;
			}
			set
			{
				this._feeAnesthesia = value;
			}
		}
		
		private int? _unitsAnesthesia;
		public virtual int? UnitsAnesthesia
		{
			get
			{
				return this._unitsAnesthesia;
			}
			set
			{
				this._unitsAnesthesia = value;
			}
		}
		
		private decimal? _feeNonAnesthesia;
		public virtual decimal? FeeNonAnesthesia
		{
			get
			{
				return this._feeNonAnesthesia;
			}
			set
			{
				this._feeNonAnesthesia = value;
			}
		}
		
		private int? _unitsNonAnesthesia;
		public virtual int? UnitsNonAnesthesia
		{
			get
			{
				return this._unitsNonAnesthesia;
			}
			set
			{
				this._unitsNonAnesthesia = value;
			}
		}
		
		private DateTime? _dateStart;
		public virtual DateTime? DateStart
		{
			get
			{
				return this._dateStart;
			}
			set
			{
				this._dateStart = value;
			}
		}
		
		private DateTime? _dateTerm;
		public virtual DateTime? DateTerm
		{
			get
			{
				return this._dateTerm;
			}
			set
			{
				this._dateTerm = value;
			}
		}
		
		private int? _minimumAge;
		public virtual int? MinimumAge
		{
			get
			{
				return this._minimumAge;
			}
			set
			{
				this._minimumAge = value;
			}
		}
		
		private int? _maximumAge;
		public virtual int? MaximumAge
		{
			get
			{
				return this._maximumAge;
			}
			set
			{
				this._maximumAge = value;
			}
		}
		
		private string _sex;
		public virtual string Sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				this._sex = value;
			}
		}
		
		private decimal? _premium;
		public virtual decimal? Premium
		{
			get
			{
				return this._premium;
			}
			set
			{
				this._premium = value;
			}
		}
		
		private decimal? _premMin;
		public virtual decimal? PremMin
		{
			get
			{
				return this._premMin;
			}
			set
			{
				this._premMin = value;
			}
		}
		
		private decimal? _premMax;
		public virtual decimal? PremMax
		{
			get
			{
				return this._premMax;
			}
			set
			{
				this._premMax = value;
			}
		}
		
		private short? _addTimeUnits;
		public virtual short? AddTimeUnits
		{
			get
			{
				return this._addTimeUnits;
			}
			set
			{
				this._addTimeUnits = value;
			}
		}
		
		private short? _hasBasicUnits;
		public virtual short? HasBasicUnits
		{
			get
			{
				return this._hasBasicUnits;
			}
			set
			{
				this._hasBasicUnits = value;
			}
		}
		
		private short? _reqManualReview;
		public virtual short? ReqManualReview
		{
			get
			{
				return this._reqManualReview;
			}
			set
			{
				this._reqManualReview = value;
			}
		}
		
		private short? _reqDiagCode;
		public virtual short? ReqDiagCode
		{
			get
			{
				return this._reqDiagCode;
			}
			set
			{
				this._reqDiagCode = value;
			}
		}
		
		private short? _reqRefDoctor;
		public virtual short? ReqRefDoctor
		{
			get
			{
				return this._reqRefDoctor;
			}
			set
			{
				this._reqRefDoctor = value;
			}
		}
		
		private short? _reqFacilityNum;
		public virtual short? ReqFacilityNum
		{
			get
			{
				return this._reqFacilityNum;
			}
			set
			{
				this._reqFacilityNum = value;
			}
		}
		
		private short? _reqAdmitDate;
		public virtual short? ReqAdmitDate
		{
			get
			{
				return this._reqAdmitDate;
			}
			set
			{
				this._reqAdmitDate = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Reconcile
	{
		private int _recID;
		public virtual int RecID
		{
			get
			{
				return this._recID;
			}
			set
			{
				this._recID = value;
			}
		}
		
		private int? _userID;
		public virtual int? UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private DateTime? _paymentDate;
		public virtual DateTime? PaymentDate
		{
			get
			{
				return this._paymentDate;
			}
			set
			{
				this._paymentDate = value;
			}
		}
		
		private string _fileName;
		public virtual string FileName
		{
			get
			{
				return this._fileName;
			}
			set
			{
				this._fileName = value;
			}
		}
		
		private decimal? _totalPaid;
		public virtual decimal? TotalPaid
		{
			get
			{
				return this._totalPaid;
			}
			set
			{
				this._totalPaid = value;
			}
		}
		
		private string _payee;
		public virtual string Payee
		{
			get
			{
				return this._payee;
			}
			set
			{
				this._payee = value;
			}
		}
		
		private string _billingCode;
		public virtual string BillingCode
		{
			get
			{
				return this._billingCode;
			}
			set
			{
				this._billingCode = value;
			}
		}
		
		private string _cheque;
		public virtual string Cheque
		{
			get
			{
				return this._cheque;
			}
			set
			{
				this._cheque = value;
			}
		}
		
		private string _billingAgent;
		public virtual string BillingAgent
		{
			get
			{
				return this._billingAgent;
			}
			set
			{
				this._billingAgent = value;
			}
		}
		
		private string _address1;
		public virtual string Address1
		{
			get
			{
				return this._address1;
			}
			set
			{
				this._address1 = value;
			}
		}
		
		private string _address2;
		public virtual string Address2
		{
			get
			{
				return this._address2;
			}
			set
			{
				this._address2 = value;
			}
		}
		
		private string _address3;
		public virtual string Address3
		{
			get
			{
				return this._address3;
			}
			set
			{
				this._address3 = value;
			}
		}
		
		private string _message;
		public virtual string Message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		
		private string _accounting;
		public virtual string Accounting
		{
			get
			{
				return this._accounting;
			}
			set
			{
				this._accounting = value;
			}
		}
		
		private decimal? _iSubmit;
		public virtual decimal? ISubmit
		{
			get
			{
				return this._iSubmit;
			}
			set
			{
				this._iSubmit = value;
			}
		}
		
		private decimal? _iPaid;
		public virtual decimal? IPaid
		{
			get
			{
				return this._iPaid;
			}
			set
			{
				this._iPaid = value;
			}
		}
		
		private decimal? _iDelete;
		public virtual decimal? IDelete
		{
			get
			{
				return this._iDelete;
			}
			set
			{
				this._iDelete = value;
			}
		}
		
		private decimal? _iAdjSubmit;
		public virtual decimal? IAdjSubmit
		{
			get
			{
				return this._iAdjSubmit;
			}
			set
			{
				this._iAdjSubmit = value;
			}
		}
		
		private decimal? _iAdjPaid;
		public virtual decimal? IAdjPaid
		{
			get
			{
				return this._iAdjPaid;
			}
			set
			{
				this._iAdjPaid = value;
			}
		}
		
		private decimal? _iRejSubmit;
		public virtual decimal? IRejSubmit
		{
			get
			{
				return this._iRejSubmit;
			}
			set
			{
				this._iRejSubmit = value;
			}
		}
		
		private decimal? _iRejPaid;
		public virtual decimal? IRejPaid
		{
			get
			{
				return this._iRejPaid;
			}
			set
			{
				this._iRejPaid = value;
			}
		}
		
		private decimal? _oSubmit;
		public virtual decimal? OSubmit
		{
			get
			{
				return this._oSubmit;
			}
			set
			{
				this._oSubmit = value;
			}
		}
		
		private decimal? _oPaid;
		public virtual decimal? OPaid
		{
			get
			{
				return this._oPaid;
			}
			set
			{
				this._oPaid = value;
			}
		}
		
		private decimal? _oAdjSubmit;
		public virtual decimal? OAdjSubmit
		{
			get
			{
				return this._oAdjSubmit;
			}
			set
			{
				this._oAdjSubmit = value;
			}
		}
		
		private decimal? _oAdjPaid;
		public virtual decimal? OAdjPaid
		{
			get
			{
				return this._oAdjPaid;
			}
			set
			{
				this._oAdjPaid = value;
			}
		}
		
		private decimal? _oRejSubmit;
		public virtual decimal? ORejSubmit
		{
			get
			{
				return this._oRejSubmit;
			}
			set
			{
				this._oRejSubmit = value;
			}
		}
		
		private decimal? _oRejPaid;
		public virtual decimal? ORejPaid
		{
			get
			{
				return this._oRejPaid;
			}
			set
			{
				this._oRejPaid = value;
			}
		}
		
		private decimal? _iAltSubmit;
		public virtual decimal? IAltSubmit
		{
			get
			{
				return this._iAltSubmit;
			}
			set
			{
				this._iAltSubmit = value;
			}
		}
		
		private decimal? _iAltPaid;
		public virtual decimal? IAltPaid
		{
			get
			{
				return this._iAltPaid;
			}
			set
			{
				this._iAltPaid = value;
			}
		}
		
		private double? _tolerance;
		public virtual double? Tolerance
		{
			get
			{
				return this._tolerance;
			}
			set
			{
				this._tolerance = value;
			}
		}
		
		private decimal? _iDelSubmit;
		public virtual decimal? IDelSubmit
		{
			get
			{
				return this._iDelSubmit;
			}
			set
			{
				this._iDelSubmit = value;
			}
		}
		
		private decimal? _iDelPaid;
		public virtual decimal? IDelPaid
		{
			get
			{
				return this._iDelPaid;
			}
			set
			{
				this._iDelPaid = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Recitem
	{
		private int? _recID;
		public virtual int? RecID
		{
			get
			{
				return this._recID;
			}
			set
			{
				this._recID = value;
			}
		}
		
		private int? _claimID;
		public virtual int? ClaimID
		{
			get
			{
				return this._claimID;
			}
			set
			{
				this._claimID = value;
			}
		}
		
		private string _mOHClaimID;
		public virtual string MOHClaimID
		{
			get
			{
				return this._mOHClaimID;
			}
			set
			{
				this._mOHClaimID = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private string _healthNumber;
		public virtual string HealthNumber
		{
			get
			{
				return this._healthNumber;
			}
			set
			{
				this._healthNumber = value;
			}
		}
		
		private string _payCode;
		public virtual string PayCode
		{
			get
			{
				return this._payCode;
			}
			set
			{
				this._payCode = value;
			}
		}
		
		private DateTime? _serviceDate;
		public virtual DateTime? ServiceDate
		{
			get
			{
				return this._serviceDate;
			}
			set
			{
				this._serviceDate = value;
			}
		}
		
		private decimal? _submitted;
		public virtual decimal? Submitted
		{
			get
			{
				return this._submitted;
			}
			set
			{
				this._submitted = value;
			}
		}
		
		private decimal? _paid;
		public virtual decimal? Paid
		{
			get
			{
				return this._paid;
			}
			set
			{
				this._paid = value;
			}
		}
		
		private string _expCode;
		public virtual string ExpCode
		{
			get
			{
				return this._expCode;
			}
			set
			{
				this._expCode = value;
			}
		}
		
		private string _serviceCode;
		public virtual string ServiceCode
		{
			get
			{
				return this._serviceCode;
			}
			set
			{
				this._serviceCode = value;
			}
		}
		
		private DateTime? _datePaid;
		public virtual DateTime? DatePaid
		{
			get
			{
				return this._datePaid;
			}
			set
			{
				this._datePaid = value;
			}
		}
		
		private string _errCode;
		public virtual string ErrCode
		{
			get
			{
				return this._errCode;
			}
			set
			{
				this._errCode = value;
			}
		}
		
		private int? _numberOfServices;
		public virtual int? NumberOfServices
		{
			get
			{
				return this._numberOfServices;
			}
			set
			{
				this._numberOfServices = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Quickprocedure
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private string _serviceCode;
		public virtual string ServiceCode
		{
			get
			{
				return this._serviceCode;
			}
			set
			{
				this._serviceCode = value;
			}
		}
		
		private string _suffix;
		public virtual string Suffix
		{
			get
			{
				return this._suffix;
			}
			set
			{
				this._suffix = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Quickpremium
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private string _serviceCode;
		public virtual string ServiceCode
		{
			get
			{
				return this._serviceCode;
			}
			set
			{
				this._serviceCode = value;
			}
		}
		
		private string _suffix;
		public virtual string Suffix
		{
			get
			{
				return this._suffix;
			}
			set
			{
				this._suffix = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Province
	{
		private string _provinceCode;
		public virtual string ProvinceCode
		{
			get
			{
				return this._provinceCode;
			}
			set
			{
				this._provinceCode = value;
			}
		}
		
		private string _provinceName;
		public virtual string ProvinceName
		{
			get
			{
				return this._provinceName;
			}
			set
			{
				this._provinceName = value;
			}
		}
		
		private int? _format;
		public virtual int? Format
		{
			get
			{
				return this._format;
			}
			set
			{
				this._format = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Provider
	{
		private int _providerID;
		public virtual int ProviderID
		{
			get
			{
				return this._providerID;
			}
			set
			{
				this._providerID = value;
			}
		}
		
		private string _provider1;
		public virtual string Provider1
		{
			get
			{
				return this._provider1;
			}
			set
			{
				this._provider1 = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Paycode
	{
		private string _payment;
		public virtual string Payment
		{
			get
			{
				return this._payment;
			}
			set
			{
				this._payment = value;
			}
		}
		
		private string _payCode;
		public virtual string PayCode
		{
			get
			{
				return this._payCode;
			}
			set
			{
				this._payCode = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Patient
	{
		private int _patientID;
		public virtual int PatientID
		{
			get
			{
				return this._patientID;
			}
			set
			{
				this._patientID = value;
			}
		}
		
		private string _healthNumber;
		public virtual string HealthNumber
		{
			get
			{
				return this._healthNumber;
			}
			set
			{
				this._healthNumber = value;
			}
		}
		
		private string _versionCode;
		public virtual string VersionCode
		{
			get
			{
				return this._versionCode;
			}
			set
			{
				this._versionCode = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private DateTime? _birthDate;
		public virtual DateTime? BirthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				this._birthDate = value;
			}
		}
		
		private string _sex;
		public virtual string Sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				this._sex = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _provinceCode;
		public virtual string ProvinceCode
		{
			get
			{
				return this._provinceCode;
			}
			set
			{
				this._provinceCode = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _homePhone;
		public virtual string HomePhone
		{
			get
			{
				return this._homePhone;
			}
			set
			{
				this._homePhone = value;
			}
		}
		
		private string _workPhone;
		public virtual string WorkPhone
		{
			get
			{
				return this._workPhone;
			}
			set
			{
				this._workPhone = value;
			}
		}
		
		private string _refMD;
		public virtual string RefMD
		{
			get
			{
				return this._refMD;
			}
			set
			{
				this._refMD = value;
			}
		}
		
		private string _famMD;
		public virtual string FamMD
		{
			get
			{
				return this._famMD;
			}
			set
			{
				this._famMD = value;
			}
		}
		
		private string _facilityCode;
		public virtual string FacilityCode
		{
			get
			{
				return this._facilityCode;
			}
			set
			{
				this._facilityCode = value;
			}
		}
		
		private DateTime? _admitDate;
		public virtual DateTime? AdmitDate
		{
			get
			{
				return this._admitDate;
			}
			set
			{
				this._admitDate = value;
			}
		}
		
		private string _notes;
		public virtual string Notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				this._notes = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Myscheduleofbenefit
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _serviceCode;
		public virtual string ServiceCode
		{
			get
			{
				return this._serviceCode;
			}
			set
			{
				this._serviceCode = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Myfacility
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _facilityCode;
		public virtual string FacilityCode
		{
			get
			{
				return this._facilityCode;
			}
			set
			{
				this._facilityCode = value;
			}
		}
		
		private string _facilityName;
		public virtual string FacilityName
		{
			get
			{
				return this._facilityName;
			}
			set
			{
				this._facilityName = value;
			}
		}
		
		private string _facilityCity;
		public virtual string FacilityCity
		{
			get
			{
				return this._facilityCity;
			}
			set
			{
				this._facilityCity = value;
			}
		}
		
		private string _facilityType;
		public virtual string FacilityType
		{
			get
			{
				return this._facilityType;
			}
			set
			{
				this._facilityType = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Mydiagnosticcode
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _dxCode;
		public virtual string DxCode
		{
			get
			{
				return this._dxCode;
			}
			set
			{
				this._dxCode = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Mriclaim
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _mRIGRP;
		public virtual int MRIGRP
		{
			get
			{
				return this._mRIGRP;
			}
			set
			{
				this._mRIGRP = value;
			}
		}
		
		private int _mRIClaimID;
		public virtual int MRIClaimID
		{
			get
			{
				return this._mRIClaimID;
			}
			set
			{
				this._mRIClaimID = value;
			}
		}
		
		private string _healthNumber;
		public virtual string HealthNumber
		{
			get
			{
				return this._healthNumber;
			}
			set
			{
				this._healthNumber = value;
			}
		}
		
		private string _versionCode;
		public virtual string VersionCode
		{
			get
			{
				return this._versionCode;
			}
			set
			{
				this._versionCode = value;
			}
		}
		
		private DateTime? _patientBirth;
		public virtual DateTime? PatientBirth
		{
			get
			{
				return this._patientBirth;
			}
			set
			{
				this._patientBirth = value;
			}
		}
		
		private string _account;
		public virtual string Account
		{
			get
			{
				return this._account;
			}
			set
			{
				this._account = value;
			}
		}
		
		private string _payCode;
		public virtual string PayCode
		{
			get
			{
				return this._payCode;
			}
			set
			{
				this._payCode = value;
			}
		}
		
		private string _referringMD;
		public virtual string ReferringMD
		{
			get
			{
				return this._referringMD;
			}
			set
			{
				this._referringMD = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private string _facilityNum;
		public virtual string FacilityNum
		{
			get
			{
				return this._facilityNum;
			}
			set
			{
				this._facilityNum = value;
			}
		}
		
		private DateTime? _admitDate;
		public virtual DateTime? AdmitDate
		{
			get
			{
				return this._admitDate;
			}
			set
			{
				this._admitDate = value;
			}
		}
		
		private string _refLab;
		public virtual string RefLab
		{
			get
			{
				return this._refLab;
			}
			set
			{
				this._refLab = value;
			}
		}
		
		private string _locCode;
		public virtual string LocCode
		{
			get
			{
				return this._locCode;
			}
			set
			{
				this._locCode = value;
			}
		}
		
		private string _errCode;
		public virtual string ErrCode
		{
			get
			{
				return this._errCode;
			}
			set
			{
				this._errCode = value;
			}
		}
		
		private string _sex;
		public virtual string Sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				this._sex = value;
			}
		}
		
		private string _prov;
		public virtual string Prov
		{
			get
			{
				return this._prov;
			}
			set
			{
				this._prov = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Mribill
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _mRIGRP;
		public virtual int MRIGRP
		{
			get
			{
				return this._mRIGRP;
			}
			set
			{
				this._mRIGRP = value;
			}
		}
		
		private int _mRIClaimID;
		public virtual int MRIClaimID
		{
			get
			{
				return this._mRIClaimID;
			}
			set
			{
				this._mRIClaimID = value;
			}
		}
		
		private int _mRIBill;
		public virtual int MRIBill
		{
			get
			{
				return this._mRIBill;
			}
			set
			{
				this._mRIBill = value;
			}
		}
		
		private string _serviceCode;
		public virtual string ServiceCode
		{
			get
			{
				return this._serviceCode;
			}
			set
			{
				this._serviceCode = value;
			}
		}
		
		private decimal? _fee;
		public virtual decimal? Fee
		{
			get
			{
				return this._fee;
			}
			set
			{
				this._fee = value;
			}
		}
		
		private int? _services;
		public virtual int? Services
		{
			get
			{
				return this._services;
			}
			set
			{
				this._services = value;
			}
		}
		
		private DateTime? _serviceDate;
		public virtual DateTime? ServiceDate
		{
			get
			{
				return this._serviceDate;
			}
			set
			{
				this._serviceDate = value;
			}
		}
		
		private string _dxCode;
		public virtual string DxCode
		{
			get
			{
				return this._dxCode;
			}
			set
			{
				this._dxCode = value;
			}
		}
		
		private string _expCode;
		public virtual string ExpCode
		{
			get
			{
				return this._expCode;
			}
			set
			{
				this._expCode = value;
			}
		}
		
		private string _mRIErr;
		public virtual string MRIErr
		{
			get
			{
				return this._mRIErr;
			}
			set
			{
				this._mRIErr = value;
			}
		}
		
		private string _expDesc;
		public virtual string ExpDesc
		{
			get
			{
				return this._expDesc;
			}
			set
			{
				this._expDesc = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Mohreject
	{
		private string _errCode;
		public virtual string ErrCode
		{
			get
			{
				return this._errCode;
			}
			set
			{
				this._errCode = value;
			}
		}
		
		private string _errDescrip;
		public virtual string ErrDescrip
		{
			get
			{
				return this._errDescrip;
			}
			set
			{
				this._errDescrip = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Mohreconcile
	{
		private string _expCode;
		public virtual string ExpCode
		{
			get
			{
				return this._expCode;
			}
			set
			{
				this._expCode = value;
			}
		}
		
		private string _expDescrip;
		public virtual string ExpDescrip
		{
			get
			{
				return this._expDescrip;
			}
			set
			{
				this._expDescrip = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Mohoffice
	{
		private string _mOHOffice;
		public virtual string MOHOffice
		{
			get
			{
				return this._mOHOffice;
			}
			set
			{
				this._mOHOffice = value;
			}
		}
		
		private string _claimCard;
		public virtual string ClaimCard
		{
			get
			{
				return this._claimCard;
			}
			set
			{
				this._claimCard = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Groupmd
	{
		private int _providerID;
		public virtual int ProviderID
		{
			get
			{
				return this._providerID;
			}
			set
			{
				this._providerID = value;
			}
		}
		
		private int? _userID;
		public virtual int? UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _gLastName;
		public virtual string GLastName
		{
			get
			{
				return this._gLastName;
			}
			set
			{
				this._gLastName = value;
			}
		}
		
		private string _gFirstName;
		public virtual string GFirstName
		{
			get
			{
				return this._gFirstName;
			}
			set
			{
				this._gFirstName = value;
			}
		}
		
		private string _gGroupCode;
		public virtual string GGroupCode
		{
			get
			{
				return this._gGroupCode;
			}
			set
			{
				this._gGroupCode = value;
			}
		}
		
		private string _gBillingCode;
		public virtual string GBillingCode
		{
			get
			{
				return this._gBillingCode;
			}
			set
			{
				this._gBillingCode = value;
			}
		}
		
		private string _gSpecialityCode;
		public virtual string GSpecialityCode
		{
			get
			{
				return this._gSpecialityCode;
			}
			set
			{
				this._gSpecialityCode = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Facility
	{
		private string _facilityCode;
		public virtual string FacilityCode
		{
			get
			{
				return this._facilityCode;
			}
			set
			{
				this._facilityCode = value;
			}
		}
		
		private string _facilityName;
		public virtual string FacilityName
		{
			get
			{
				return this._facilityName;
			}
			set
			{
				this._facilityName = value;
			}
		}
		
		private string _facilityType;
		public virtual string FacilityType
		{
			get
			{
				return this._facilityType;
			}
			set
			{
				this._facilityType = value;
			}
		}
		
		private string _facilityCity;
		public virtual string FacilityCity
		{
			get
			{
				return this._facilityCity;
			}
			set
			{
				this._facilityCity = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Edtfile
	{
		private int? _userID;
		public virtual int? UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private DateTime? _eDTDate;
		public virtual DateTime? EDTDate
		{
			get
			{
				return this._eDTDate;
			}
			set
			{
				this._eDTDate = value;
			}
		}
		
		private string _fileName;
		public virtual string FileName
		{
			get
			{
				return this._fileName;
			}
			set
			{
				this._fileName = value;
			}
		}
		
		private string _reason;
		public virtual string Reason
		{
			get
			{
				return this._reason;
			}
			set
			{
				this._reason = value;
			}
		}
		
		private string _recordLength;
		public virtual string RecordLength
		{
			get
			{
				return this._recordLength;
			}
			set
			{
				this._recordLength = value;
			}
		}
		
		private string _record;
		public virtual string Record
		{
			get
			{
				return this._record;
			}
			set
			{
				this._record = value;
			}
		}
		
		private string _file;
		public virtual string File
		{
			get
			{
				return this._file;
			}
			set
			{
				this._file = value;
			}
		}
		
		private DateTime? _mDate;
		public virtual DateTime? MDate
		{
			get
			{
				return this._mDate;
			}
			set
			{
				this._mDate = value;
			}
		}
		
		private DateTime? _pDate;
		public virtual DateTime? PDate
		{
			get
			{
				return this._pDate;
			}
			set
			{
				this._pDate = value;
			}
		}
		
		private int? _recID;
		public virtual int? RecID
		{
			get
			{
				return this._recID;
			}
			set
			{
				this._recID = value;
			}
		}
		
		private string _mOHBatch;
		public virtual string MOHBatch
		{
			get
			{
				return this._mOHBatch;
			}
			set
			{
				this._mOHBatch = value;
			}
		}
		
		private string _batchSeq;
		public virtual string BatchSeq
		{
			get
			{
				return this._batchSeq;
			}
			set
			{
				this._batchSeq = value;
			}
		}
		
		private int? _batchClaims;
		public virtual int? BatchClaims
		{
			get
			{
				return this._batchClaims;
			}
			set
			{
				this._batchClaims = value;
			}
		}
		
		private int? _batchRecords;
		public virtual int? BatchRecords
		{
			get
			{
				return this._batchRecords;
			}
			set
			{
				this._batchRecords = value;
			}
		}
		
		private string _batchErr;
		public virtual string BatchErr
		{
			get
			{
				return this._batchErr;
			}
			set
			{
				this._batchErr = value;
			}
		}
		
		private short? _batchOk;
		public virtual short? BatchOk
		{
			get
			{
				return this._batchOk;
			}
			set
			{
				this._batchOk = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Edt
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int? _port;
		public virtual int? Port
		{
			get
			{
				return this._port;
			}
			set
			{
				this._port = value;
			}
		}
		
		private int? _baud;
		public virtual int? Baud
		{
			get
			{
				return this._baud;
			}
			set
			{
				this._baud = value;
			}
		}
		
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private string _userPass;
		public virtual string UserPass
		{
			get
			{
				return this._userPass;
			}
			set
			{
				this._userPass = value;
			}
		}
		
		private string _newPass;
		public virtual string NewPass
		{
			get
			{
				return this._newPass;
			}
			set
			{
				this._newPass = value;
			}
		}
		
		private string _dPrefix;
		public virtual string DPrefix
		{
			get
			{
				return this._dPrefix;
			}
			set
			{
				this._dPrefix = value;
			}
		}
		
		private string _eDTNum;
		public virtual string EDTNum
		{
			get
			{
				return this._eDTNum;
			}
			set
			{
				this._eDTNum = value;
			}
		}
		
		private DateTime? _lastConnect;
		public virtual DateTime? LastConnect
		{
			get
			{
				return this._lastConnect;
			}
			set
			{
				this._lastConnect = value;
			}
		}
		
		private string _hAFile;
		public virtual string HAFile
		{
			get
			{
				return this._hAFile;
			}
			set
			{
				this._hAFile = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Doctor
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _billingCode;
		public virtual string BillingCode
		{
			get
			{
				return this._billingCode;
			}
			set
			{
				this._billingCode = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private string _groupNum;
		public virtual string GroupNum
		{
			get
			{
				return this._groupNum;
			}
			set
			{
				this._groupNum = value;
			}
		}
		
		private string _specialityCode;
		public virtual string SpecialityCode
		{
			get
			{
				return this._specialityCode;
			}
			set
			{
				this._specialityCode = value;
			}
		}
		
		private string _mOHOffice;
		public virtual string MOHOffice
		{
			get
			{
				return this._mOHOffice;
			}
			set
			{
				this._mOHOffice = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _provinceCode;
		public virtual string ProvinceCode
		{
			get
			{
				return this._provinceCode;
			}
			set
			{
				this._provinceCode = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _phone;
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				this._phone = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _facilityCode;
		public virtual string FacilityCode
		{
			get
			{
				return this._facilityCode;
			}
			set
			{
				this._facilityCode = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Diagnosticcode
	{
		private string _dxCode;
		public virtual string DxCode
		{
			get
			{
				return this._dxCode;
			}
			set
			{
				this._dxCode = value;
			}
		}
		
		private string _dxName;
		public virtual string DxName
		{
			get
			{
				return this._dxName;
			}
			set
			{
				this._dxName = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Claim
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _claimID;
		public virtual int ClaimID
		{
			get
			{
				return this._claimID;
			}
			set
			{
				this._claimID = value;
			}
		}
		
		private int? _batchID;
		public virtual int? BatchID
		{
			get
			{
				return this._batchID;
			}
			set
			{
				this._batchID = value;
			}
		}
		
		private int? _patientID;
		public virtual int? PatientID
		{
			get
			{
				return this._patientID;
			}
			set
			{
				this._patientID = value;
			}
		}
		
		private string _payCode;
		public virtual string PayCode
		{
			get
			{
				return this._payCode;
			}
			set
			{
				this._payCode = value;
			}
		}
		
		private string _refMDCode;
		public virtual string RefMDCode
		{
			get
			{
				return this._refMDCode;
			}
			set
			{
				this._refMDCode = value;
			}
		}
		
		private string _facilityCode;
		public virtual string FacilityCode
		{
			get
			{
				return this._facilityCode;
			}
			set
			{
				this._facilityCode = value;
			}
		}
		
		private DateTime? _admitDate;
		public virtual DateTime? AdmitDate
		{
			get
			{
				return this._admitDate;
			}
			set
			{
				this._admitDate = value;
			}
		}
		
		private string _refLabCode;
		public virtual string RefLabCode
		{
			get
			{
				return this._refLabCode;
			}
			set
			{
				this._refLabCode = value;
			}
		}
		
		private short? _manualReview;
		public virtual short? ManualReview
		{
			get
			{
				return this._manualReview;
			}
			set
			{
				this._manualReview = value;
			}
		}
		
		private DateTime _dateCreated;
		public virtual DateTime DateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				this._dateCreated = value;
			}
		}
		
		private decimal? _claimFee;
		public virtual decimal? ClaimFee
		{
			get
			{
				return this._claimFee;
			}
			set
			{
				this._claimFee = value;
			}
		}
		
		private string _status;
		public virtual string Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private string _errMsg;
		public virtual string ErrMsg
		{
			get
			{
				return this._errMsg;
			}
			set
			{
				this._errMsg = value;
			}
		}
		
		private decimal? _claimPaid;
		public virtual decimal? ClaimPaid
		{
			get
			{
				return this._claimPaid;
			}
			set
			{
				this._claimPaid = value;
			}
		}
		
		private int? _providerID;
		public virtual int? ProviderID
		{
			get
			{
				return this._providerID;
			}
			set
			{
				this._providerID = value;
			}
		}
		
		private string _mRICode;
		public virtual string MRICode
		{
			get
			{
				return this._mRICode;
			}
			set
			{
				this._mRICode = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Bill
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _claimID;
		public virtual int ClaimID
		{
			get
			{
				return this._claimID;
			}
			set
			{
				this._claimID = value;
			}
		}
		
		private int _billID;
		public virtual int BillID
		{
			get
			{
				return this._billID;
			}
			set
			{
				this._billID = value;
			}
		}
		
		private DateTime? _serviceDate;
		public virtual DateTime? ServiceDate
		{
			get
			{
				return this._serviceDate;
			}
			set
			{
				this._serviceDate = value;
			}
		}
		
		private string _serviceCode;
		public virtual string ServiceCode
		{
			get
			{
				return this._serviceCode;
			}
			set
			{
				this._serviceCode = value;
			}
		}
		
		private string _suffix;
		public virtual string Suffix
		{
			get
			{
				return this._suffix;
			}
			set
			{
				this._suffix = value;
			}
		}
		
		private string _dxCode;
		public virtual string DxCode
		{
			get
			{
				return this._dxCode;
			}
			set
			{
				this._dxCode = value;
			}
		}
		
		private DateTime? _startTime;
		public virtual DateTime? StartTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				this._startTime = value;
			}
		}
		
		private DateTime? _endTime;
		public virtual DateTime? EndTime
		{
			get
			{
				return this._endTime;
			}
			set
			{
				this._endTime = value;
			}
		}
		
		private int? _timeUnits;
		public virtual int? TimeUnits
		{
			get
			{
				return this._timeUnits;
			}
			set
			{
				this._timeUnits = value;
			}
		}
		
		private int? _numberOfServices;
		public virtual int? NumberOfServices
		{
			get
			{
				return this._numberOfServices;
			}
			set
			{
				this._numberOfServices = value;
			}
		}
		
		private decimal? _unitAmount;
		public virtual decimal? UnitAmount
		{
			get
			{
				return this._unitAmount;
			}
			set
			{
				this._unitAmount = value;
			}
		}
		
		private decimal? _feeSubmitted;
		public virtual decimal? FeeSubmitted
		{
			get
			{
				return this._feeSubmitted;
			}
			set
			{
				this._feeSubmitted = value;
			}
		}
		
		private decimal? _feePaid;
		public virtual decimal? FeePaid
		{
			get
			{
				return this._feePaid;
			}
			set
			{
				this._feePaid = value;
			}
		}
		
		private DateTime? _datePaid;
		public virtual DateTime? DatePaid
		{
			get
			{
				return this._datePaid;
			}
			set
			{
				this._datePaid = value;
			}
		}
		
		private string _expCode;
		public virtual string ExpCode
		{
			get
			{
				return this._expCode;
			}
			set
			{
				this._expCode = value;
			}
		}
		
		private string _errCode;
		public virtual string ErrCode
		{
			get
			{
				return this._errCode;
			}
			set
			{
				this._errCode = value;
			}
		}
		
		private string _mRICode;
		public virtual string MRICode
		{
			get
			{
				return this._mRICode;
			}
			set
			{
				this._mRICode = value;
			}
		}
		
	}
}
namespace iBill.Data	
{
	public partial class Batch
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private int _batchID;
		public virtual int BatchID
		{
			get
			{
				return this._batchID;
			}
			set
			{
				this._batchID = value;
			}
		}
		
		private string _mOHOffice;
		public virtual string MOHOffice
		{
			get
			{
				return this._mOHOffice;
			}
			set
			{
				this._mOHOffice = value;
			}
		}
		
		private string _groupNum;
		public virtual string GroupNum
		{
			get
			{
				return this._groupNum;
			}
			set
			{
				this._groupNum = value;
			}
		}
		
		private string _providerNum;
		public virtual string ProviderNum
		{
			get
			{
				return this._providerNum;
			}
			set
			{
				this._providerNum = value;
			}
		}
		
		private string _specCode;
		public virtual string SpecCode
		{
			get
			{
				return this._specCode;
			}
			set
			{
				this._specCode = value;
			}
		}
		
		private int? _h;
		public virtual int? H
		{
			get
			{
				return this._h;
			}
			set
			{
				this._h = value;
			}
		}
		
		private int? _r;
		public virtual int? R
		{
			get
			{
				return this._r;
			}
			set
			{
				this._r = value;
			}
		}
		
		private int? _t;
		public virtual int? T
		{
			get
			{
				return this._t;
			}
			set
			{
				this._t = value;
			}
		}
		
		private int? _records;
		public virtual int? Records
		{
			get
			{
				return this._records;
			}
			set
			{
				this._records = value;
			}
		}
		
		private decimal? _total;
		public virtual decimal? Total
		{
			get
			{
				return this._total;
			}
			set
			{
				this._total = value;
			}
		}
		
		private DateTime? _submitDate;
		public virtual DateTime? SubmitDate
		{
			get
			{
				return this._submitDate;
			}
			set
			{
				this._submitDate = value;
			}
		}
		
		private string _fileName;
		public virtual string FileName
		{
			get
			{
				return this._fileName;
			}
			set
			{
				this._fileName = value;
			}
		}
		
		private string _batchStatus;
		public virtual string BatchStatus
		{
			get
			{
				return this._batchStatus;
			}
			set
			{
				this._batchStatus = value;
			}
		}
		
	}
}
#pragma warning restore 1591
